/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbl_uts;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M. HASNAN AL ABIYYU
 */
public class Buku extends javax.swing.JFrame {

    private final Connection Connection = ConnectDb.getConnectDb().getConnection();
    private final ArrayList<String[]> dataList = new ArrayList<>();
    private final String[] columns = {"id_buku", "judul_buku", "penerbit", "stok"};

    private final Connection connection = ConnectDb.getConnectDb().getConnection();

    public Buku() {
        initComponents();
        getAllData();
        refreshModel();
        id_auto();
    }

    public final void getAllData() {
        try {
            dataList.clear();
            String sql = "SELECT * FROM buku;";
            PreparedStatement ps = Connection.prepareStatement(sql);
            ps.execute();
            final ResultSet data = ps.getResultSet();
            while (data.next()) {
                final String[] row = new String[]{
                    data.getString("id_buku"),
                    data.getString("judul_buku"),                  
                    data.getString("penerbit"),
                    data.getString("stok")};
                    dataList.add(row);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.add(new JScrollPane(table));
        frame.pack();
        frame.setVisible(true);

    }

    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);
        for (String[] data : dataList) {
            model.addRow(data);
        }
        tblbuku.setModel(model);
    }
    
        public final void id_auto() {
        try {
            final Statement stat = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            final String sql = "select max (right(id_buku, 1)) as no from buku";
            final ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                if (rs.first() == false) {
                    txtidbuku.setText("B0001");
                } else {
                    rs.last();
                    int set_id = rs.getInt(1) + 1;
                    String no = String.valueOf(set_id);
                    int id_next = no.length();
                    for (int a = 0; a < 4 - id_next; a++) {
                        no = "0" + no;
                    }
                    txtidbuku.setText("B" + no);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
        public void cari() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("id_buku");
        tbl.addColumn("judul_buku");
        tbl.addColumn("penerbit");
        tbl.addColumn("stok");

        try {
            String sql = "Select*from buku where judul_buku like '%" + txtcaribuku.getText() + "%'";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("id_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("penerbit"),
                    rs.getString("stok"),
                });
                tblbuku.setModel(tbl);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidbuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtjudulbuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpenerbitbuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstokbuku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbuku = new javax.swing.JTable();
        btnsimpanbuku = new javax.swing.JButton();
        btnupdatebuku = new javax.swing.JButton();
        btnhapusbuku = new javax.swing.JButton();
        txtcaribuku = new javax.swing.JTextField();
        btncaribuku = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA BUKU");

        jLabel2.setText("ID BUKU");

        jLabel3.setText("JUDUL BUKU");

        txtjudulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulbukuActionPerformed(evt);
            }
        });

        jLabel4.setText("PENERBIT");

        txtpenerbitbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenerbitbukuActionPerformed(evt);
            }
        });

        jLabel5.setText("STOK BUKU");

        tblbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbuku);

        btnsimpanbuku.setText("Simpan");
        btnsimpanbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanbukuActionPerformed(evt);
            }
        });

        btnupdatebuku.setText("Update");
        btnupdatebuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatebukuActionPerformed(evt);
            }
        });

        btnhapusbuku.setText("Hapus");
        btnhapusbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusbukuActionPerformed(evt);
            }
        });

        btncaribuku.setText("Cari");
        btncaribuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaribukuActionPerformed(evt);
            }
        });

        jLabel6.setText("*masukkan judul buku");

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpanbuku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(btnupdatebuku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtjudulbuku)
                                        .addComponent(txtpenerbitbuku)
                                        .addComponent(txtstokbuku, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(txtidbuku))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnhapusbuku)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btncaribuku))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnback)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcaribuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaribuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpenerbitbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtstokbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpanbuku)
                            .addComponent(btnupdatebuku))
                        .addGap(18, 18, 18)
                        .addComponent(btnhapusbuku))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjudulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulbukuActionPerformed

    private void txtpenerbitbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenerbitbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitbukuActionPerformed

    private void btnsimpanbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanbukuActionPerformed
        // TODO add your handling code here:
        try {
            final String sql = "INSERT INTO buku(id_buku, judul_buku, penerbit, stok) VALUES (?,?,?,?)";
            final PreparedStatement ps = connection.prepareStatement(sql);
            if (txtidbuku.getText().isEmpty() || txtjudulbuku.getText().isEmpty() || txtpenerbitbuku.getText().isEmpty() || txtstokbuku.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi Semua Kolom terlebih dahulu");
            } else {
                ps.setString(1, txtidbuku.getText());
                ps.setString(2, txtjudulbuku.getText());
                ps.setString(3, txtpenerbitbuku.getText());
                ps.setInt(4, Integer.parseInt(txtstokbuku.getText()));
                ps.execute();
                JOptionPane.showMessageDialog(null, "Berhasil di simpan");
            }
            this.getAllData();
            this.refreshModel();
            this.id_auto();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal disimpan");
            System.out.println(e.getMessage());
        }
        
        txtjudulbuku.setText("");
        txtpenerbitbuku.setText("");
        txtstokbuku.setText("");
    }//GEN-LAST:event_btnsimpanbukuActionPerformed

    private void btncaribukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaribukuActionPerformed
        // TODO add your handling code here:
        this.cari();
    }//GEN-LAST:event_btncaribukuActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        txtidbuku.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void btnupdatebukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatebukuActionPerformed
        // TODO add your handling code here:
        String idBuku = txtidbuku.getText();
        String judul = txtjudulbuku.getText();
        String penerbit = txtpenerbitbuku.getText();
        try {
            final String sql = "Update buku set judul_buku= ?, penerbit =?, stok =? where id_buku= ?";
            final PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, judul);
            pst.setString(2, penerbit);
            pst.setInt(3, Integer.parseInt(txtstokbuku.getText()));
            pst.setString(4, idBuku);
            pst.executeUpdate();

            this.getAllData();
            this.refreshModel();
            this.id_auto();

            JOptionPane.showMessageDialog(this, "Berhasil Memperbarui");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Memperbarui");
        }
        txtjudulbuku.setText("");
        txtpenerbitbuku.setText("");
        txtstokbuku.setText("");
    }//GEN-LAST:event_btnupdatebukuActionPerformed

    private void btnhapusbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusbukuActionPerformed
        // TODO add your handling code here:
        try {
            String id_buku = !txtidbuku.getText().trim().isEmpty() ? txtidbuku.getText().trim() : tblbuku.getValueAt(tblbuku.getSelectedRow(), 0).toString();
            String sql = "delete from buku where id_buku = ?";
            PreparedStatement ps = Connection.prepareStatement(sql);
            ps.setString(1, id_buku);
            ps.execute();
            this.getAllData();
            this.refreshModel();
            this.id_auto();

            JOptionPane.showMessageDialog(this, "Data behasil dihapus");
        } catch (SQLException | ArrayIndexOutOfBoundsException ex) {
            System.out.println(ex.getMessage());
        }

        txtjudulbuku.setText("");
        txtpenerbitbuku.setText("");
        txtstokbuku.setText("");
    }//GEN-LAST:event_btnhapusbukuActionPerformed

    private void tblbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbukuMouseClicked
        // TODO add your handling code here:
        int row = tblbuku.getSelectedRow();
        txtidbuku.setText(tblbuku.getValueAt(row, 0).toString());
        txtjudulbuku.setText(tblbuku.getValueAt(row, 1).toString());
        txtpenerbitbuku.setText(tblbuku.getValueAt(row, 2).toString());
        txtstokbuku.setText(tblbuku.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tblbukuMouseClicked

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TampilanAwal frame = new TampilanAwal();
        frame.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncaribuku;
    private javax.swing.JButton btnhapusbuku;
    private javax.swing.JButton btnsimpanbuku;
    private javax.swing.JButton btnupdatebuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbuku;
    private javax.swing.JTextField txtcaribuku;
    private javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtjudulbuku;
    private javax.swing.JTextField txtpenerbitbuku;
    private javax.swing.JTextField txtstokbuku;
    // End of variables declaration//GEN-END:variables
}
